# Настройки базы данных H2 (ТОЛЬКО ЧТЕНИЕ!)
spring.datasource.url=jdbc:h2:file:./transaction;MODE=LEGACY;DB_CLOSE_ON_EXIT=FALSE;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

# Отключаем инициализацию схемы (чтобы Spring не создавал свои таблицы)
spring.sql.init.mode=never

# Настройки логирования
logging.level.com.bank.recommendation=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

# Настройки H2 консоли (опционально, если хотите смотреть БД через браузер)
spring.h2.console.enabled=false

# Порт приложения
server.port=8080